config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get '/about' => 'static_pages#about_us'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  EMAIL_REGEX = /\A([a-z0-9][\._\-]?)+@(\w)+(\.([a-z])+)+\z/i

  validates :name, presence: true
  validates :email, presence: true, format: { with: EMAIL_REGEX }

  has_secure_password

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    password = params[:session][:password]
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(password)
      flash[:success] = 'Welcome'
      login(user)
      redirect_to root_url
    else
      flash[:danger] = 'Email or password are incorrect'
      render 'new'
    end
  end

  def destroy
    if logged_in?
      logout
    end
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about_us
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_title(title)
    title.empty? ? "UCBTweet" : "#{title} | UCBTweet"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    if logged_in?
      session.delete(:user_id)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= get_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Curso Rails</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" data-toggle="dropdown">
                <%= current_user.name %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Show', user_path(current_user) %></li>
                <li><%= link_to 'Edit', edit_user_path(current_user) %></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Register', new_user_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/about_us.html.erb
<% provide(:title, "About") %>

<h1>Hola</h1>
<%= image_tag 'ayuda.jpg', height: 200 %>
<h2>Video of our team ^^</h1>
<iframe width="640" height="360" src="https://www.youtube.com/embed/KPDqb45P2Mg" frameborder="0" allowfullscreen></iframe>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1 class="text-center">Hello World</h1>
  <p>
    This is my first rails application
  </p>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>

<h1 class="text-center">Edit User</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Update", class: 'btn btn-primary text-center form-control' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>

<h1 class="text-center">Register</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Login", class: 'btn btn-primary text-center form-control' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1> <%= @user.name %></h1>
<p>
  <%= @user.email %>
</p>

<ul>
  <% @user.comments.each do |c| %>
    <li><%= c.title %></li>
  <% end %>
</ul>